// Unit Values
const unitValues = [
    {
        name: [
            "Dracheneier",
            "Dragon Eggs",
            "",
            "",
            "",
            "",
        ],
        attack: "1",
        defense: "1",
        life: "80",
        tpv: "4",
        capacity: "100",
        points: "2251",
        costs: {
            production: {
                essences: "60000",
                crystals: "38000",
                stones: "51000",
                gold: "44000",
                mana: "3000",
            },
            revival: {
                stones: "60000",
                mushrooms: "3000",
            },
        },
        sentinel: false,
        experience: "99",
    },
    {
        name: [
            "Einhornwagen",
            "Unicorn Carts",
            "",
            "",
            "",
            "",
        ],
        attack: "0",
        defense: "0",
        life: "20",
        tpv: "2",
        capacity: "2000",
        points: "17",
        costs: {
            production: {
                essences: "1000",
                crystals: "800",
                stones: "400",
                gold: "100",
                mana: "10",
            },
            revival: {
                stones: "200",
                mushrooms: "10",
            },
        },
        sentinel: false,
        experience: "0.3",
    },
    {
        name: [
            "Kobold",
            "Goblins",
            "",
            "",
            "",
            "",
        ],
        attack: "1",
        defense: "1",
        life: "25",
        tpv: "4",
        capacity: "0",
        points: "5",
        costs: {
            production: {
                essences: "430",
                crystals: "270",
                stones: "120",
                gold: "0",
                mana: "3",
            },
            revival: {
                stones: "60",
                mushrooms: "3",
            },
        },
        sentinel: false,
        experience: "0.2",
    },
    {
        name: [
            "Eiskrieger",
            "Ice Warrior",
            "",
            "",
            "",
            "",
        ],
        attack: "2",
        defense: "2",
        life: "40",
        tpv: "2",
        capacity: "0",
        points: "10",
        costs: {
            production: {
                essences: "530",
                crystals: "470",
                stones: "190",
                gold: "150",
                mana: "5",
            },
            revival: {
                stones: "100",
                mushrooms: "5",
            },
        },
        sentinel: false,
        experience: "0.4",
    },
    {
        name: [
            "Kinder der Macht",
            "Children of Power",
            "",
            "",
            "",
            "",
        ],
        attack: "3",
        defense: "3",
        life: "9",
        tpv: "4",
        capacity: "60",
        points: "6",
        costs: {
            production: {
                essences: "320",
                crystals: "420",
                stones: "120",
                gold: "20",
                mana: "3",
            },
            revival: {
                stones: "60",
                mushrooms: "3",
            },
        },
        sentinel: false,
        experience: "0.3",
    },
    {
        name: [
            "Hysterische Zentaurin",
            "Hysterical Centauride",
            "",
            "",
            "",
            "",
        ],
        attack: "7",
        defense: "7",
        life: "22",
        tpv: "2",
        capacity: "210",
        points: "12",
        costs: {
            production: {
                essences: "480",
                crystals: "525",
                stones: "240",
                gold: "140",
                mana: "7",
            },
            revival: {
                stones: "140",
                mushrooms: "7",
            },
        },
        sentinel: false,
        experience: "0.5",
    },
    {
        name: [
            "Kriegerpriester",
            "Warrior Priests",
            "",
            "",
            "",
            "",
        ],
        attack: "4",
        defense: "4",
        life: "85",
        tpv: "3",
        capacity: "0",
        points: "19",
        costs: {
            production: {
                essences: "630",
                crystals: "570",
                stones: "280",
                gold: "300",
                mana: "10",
            },
            revival: {
                stones: "200",
                mushrooms: "10",
            },
        },
        sentinel: false,
        experience: "0.8",
    },
    {
        name: [
            "Wilde Zentauren",
            "Wild Centaurs",
            "",
            "",
            "",
            "",
        ],
        attack: "15",
        defense: "13",
        life: "42",
        tpv: "2",
        capacity: "390",
        points: "23",
        costs: {
            production: {
                essences: "760",
                crystals: "1100",
                stones: "420",
                gold: "230",
                mana: "13",
            },
            revival: {
                stones: "260",
                mushrooms: "13",
            },
        },
        sentinel: false,
        experience: "0.9",
    },
    {
        name: [
            "Axtschwingende Zwerge",
            "Axe Swinging Dwarves",
            "",
            "",
            "",
            "",
        ],
        attack: "7",
        defense: "8",
        life: "180",
        tpv: "3",
        capacity: "0",
        points: "35",
        costs: {
            production: {
                essences: "1300",
                crystals: "850",
                stones: "900",
                gold: "370",
                mana: "19",
            },
            revival: {
                stones: "380",
                mushrooms: "19",
            },
        },
        sentinel: false,
        experience: "1.5",
    },
    {
        name: [
            "Elfenbogenschützen",
            "Elf Rangers",
            "",
            "",
            "",
            "",
        ],
        attack: "22",
        defense: "24",
        life: "80",
        tpv: "3",
        capacity: "420",
        points: "40",
        costs: {
            production: {
                essences: "900",
                crystals: "1500",
                stones: "710",
                gold: "600",
                mana: "21",
            },
            revival: {
                stones: "420",
                mushrooms: "21",
            },
        },
        sentinel: false,
        experience: "1.6",
    },
    {
        name: [
            "Doppelaxtzwerge",
            "Doubleedged Axe Dwarves",
            "",
            "",
            "",
            "",
        ],
        attack: "12",
        defense: "10",
        life: "250",
        tpv: "4",
        capacity: "0",
        points: "49",
        costs: {
            production: {
                essences: "1700",
                crystals: "1200",
                stones: "1150",
                gold: "600",
                mana: "25",
            },
            revival: {
                stones: "500",
                mushrooms: "25",
            },
        },
        sentinel: false,
        experience: "1.9",
    },
    {
        name: [
            "Singende Halbriesen",
            "Singing Half Giants",
            "",
            "",
            "",
            "",
        ],
        attack: "25",
        defense: "25",
        life: "600",
        tpv: "2",
        capacity: "580",
        points: "105",
        costs: {
            production: {
                essences: "6300",
                crystals: "2200",
                stones: "1800",
                gold: "1300",
                mana: "58",
            },
            revival: {
                stones: "1160",
                mushrooms: "58",
            },
        },
        sentinel: false,
        experience: "4.2",
    },
    {
        name: [
            "Steinwerfende Bergtrolle",
            "Stone Throwing Trolls",
            "",
            "",
            "",
            "",
        ],
        attack: "34",
        defense: "34",
        life: "1000",
        tpv: "4",
        capacity: "0",
        points: "154",
        costs: {
            production: {
                essences: "5400",
                crystals: "4100",
                stones: "5100",
                gold: "1350",
                mana: "80",
            },
            revival: {
                stones: "1600",
                mushrooms: "80",
            },
        },
        sentinel: false,
        experience: "5.9",
    },
    {
        name: [
            "Baumriese",
            "Tree Giants",
            "",
            "",
            "",
            "",
        ],
        attack: "53",
        defense: "53",
        life: "160",
        tpv: "4",
        capacity: "840",
        points: "77",
        costs: {
            production: {
                essences: "4000",
                crystals: "4400",
                stones: "700",
                gold: "1000",
                mana: "42",
            },
            revival: {
                stones: "840",
                mushrooms: "42",
            },
        },
        sentinel: false,
        experience: "3.1",
    },
    {
        name: [
            "Elfenmagier",
            "Elf Mages",
            "",
            "",
            "",
            "",
        ],
        attack: "82",
        defense: "82",
        life: "225",
        tpv: "2",
        capacity: "1300",
        points: "122",
        costs: {
            production: {
                essences: "3500",
                crystals: "4700",
                stones: "1000",
                gold: "2000",
                mana: "65",
            },
            revival: {
                stones: "1300",
                mushrooms: "65",
            },
        },
        sentinel: false,
        experience: "4.8",
    },
    {
        name: [
            "Feuerfeen",
            "Fire Fairies",
            "",
            "",
            "",
            "",
        ],
        attack: "25",
        defense: "25",
        life: "25",
        tpv: "2",
        capacity: "180",
        points: "30",
        costs: {
            production: {
                essences: "500",
                crystals: "500",
                stones: "500",
                gold: "500",
                mana: "20",
            },
            revival: {
                stones: "400",
                mushrooms: "20",
            },
        },
        sentinel: false,
        experience: "1.3",
    },
    {
        name: [
            "Sturmfeen",
            "Storm Fairies",
            "",
            "",
            "",
            "",
        ],
        attack: "0",
        defense: "10",
        life: "100",
        tpv: "2",
        capacity: "0",
        points: "33",
        costs: {
            production: {
                essences: "1700",
                crystals: "2000",
                stones: "370",
                gold: "280",
                mana: "20",
            },
            revival: {
                stones: "400",
                mushrooms: "20",
            },
        },
        sentinel: false,
        experience: "1.5",
    },
    {
        name: [
            "Salamander",
            "Salamanders",
            "",
            "",
            "",
            "",
        ],
        attack: "0",
        defense: "1",
        life: "4",
        tpv: "4",
        capacity: "0",
        points: "1",
        costs: {
            production: {
                essences: "0",
                crystals: "0",
                stones: "0",
                gold: "0",
                mana: "0",
            },
            revival: {
                stones: "0",
                mushrooms: "0",
            },
        },
        sentinel: true,
        experience: "0",
    },
    {
        name: [
            "Wurzelwichte",
            "Root Wights",
            "",
            "",
            "",
            "",
        ],
        attack: "1",
        defense: "1",
        life: "2",
        tpv: "2",
        capacity: "90",
        points: "1",
        costs: {
            production: {
                essences: "0",
                crystals: "0",
                stones: "0",
                gold: "0",
                mana: "0",
            },
            revival: {
                stones: "0",
                mushrooms: "0",
            },
        },
        sentinel: true,
        experience: "0.2",
    },
    {
        name: [
            "Fleischhummeln",
            "Meat Bumblebees",
            "",
            "",
            "",
            "",
        ],
        attack: "0",
        defense: "2",
        life: "12",
        tpv: "4",
        capacity: "0",
        points: "0",
        costs: {
            production: {
                essences: "0",
                crystals: "0",
                stones: "0",
                gold: "0",
                mana: "0",
            },
            revival: {
                stones: "0",
                mushrooms: "0",
            },
        },
        sentinel: true,
        experience: "0",
    },
    {
        name: [
            "Skarabaeus",
            "Scarabs",
            "",
            "",
            "",
            "",
        ],
        attack: "0",
        defense: "2",
        life: "16",
        tpv: "4",
        capacity: "0",
        points: "0",
        costs: {
            production: {
                essences: "0",
                crystals: "0",
                stones: "0",
                gold: "0",
                mana: "0",
            },
            revival: {
                stones: "0",
                mushrooms: "0",
            },
        },
        sentinel: true,
        experience: "0",
    },
    {
        name: [
            "Gnome",
            "Gnomes",
            "",
            "",
            "",
            "",
        ],
        attack: "0",
        defense: "3",
        life: "20",
        tpv: "4",
        capacity: "0",
        points: "1",
        costs: {
            production: {
                essences: "0",
                crystals: "0",
                stones: "0",
                gold: "0",
                mana: "0",
            },
            revival: {
                stones: "0",
                mushrooms: "0",
            },
        },
        sentinel: true,
        experience: "0",
    },
    {
        name: [
            "Irrlichter",
            "Will-O'-The-Wisps",
            "",
            "",
            "",
            "",
        ],
        attack: "0",
        defense: "3",
        life: "24",
        tpv: "4",
        capacity: "0",
        points: "1",
        costs: {
            production: {
                essences: "0",
                crystals: "0",
                stones: "0",
                gold: "0",
                mana: "0",
            },
            revival: {
                stones: "0",
                mushrooms: "0",
            },
        },
        sentinel: true,
        experience: "0",
    },
    {
        name: [
            "Skrälinge",
            "Skraelings",
            "",
            "",
            "",
            "",
        ],
        attack: "0",
        defense: "4",
        life: "28",
        tpv: "4",
        capacity: "0",
        points: "1",
        costs: {
            production: {
                essences: "0",
                crystals: "0",
                stones: "0",
                gold: "0",
                mana: "0",
            },
            revival: {
                stones: "0",
                mushrooms: "0",
            },
        },
        sentinel: true,
        experience: "0",
    },
    {
        name: [
            "Warzengiftratten",
            "Wart Venom Rats",
            "",
            "",
            "",
            "",
        ],
        attack: "0",
        defense: "4",
        life: "32",
        tpv: "4",
        capacity: "0",
        points: "1",
        costs: {
            production: {
                essences: "0",
                crystals: "0",
                stones: "0",
                gold: "0",
                mana: "0",
            },
            revival: {
                stones: "0",
                mushrooms: "0",
            },
        },
        sentinel: true,
        experience: "0",
    },
    {
        name: [
            "Sylphen",
            "Sylphs",
            "",
            "",
            "",
            "",
        ],
        attack: "0",
        defense: "5",
        life: "36",
        tpv: "4",
        capacity: "0",
        points: "1",
        costs: {
            production: {
                essences: "0",
                crystals: "0",
                stones: "0",
                gold: "0",
                mana: "0",
            },
            revival: {
                stones: "0",
                mushrooms: "0",
            },
        },
        sentinel: true,
        experience: "0",
    },
{
        name: [
            "Midgardschlangen",
            "Midgard Snakes",
            "",
            "",
            "",
            "",
        ],
        attack: "4",
        defense: "4",
        life: "60",
        tpv: "2",
        capacity: "80",
        points: "16",
        costs: {
            production: {
                essences: "0",
                crystals: "0",
                stones: "0",
                gold: "0",
                mana: "0",
            },
            revival: {
                stones: "0",
                mushrooms: "0",
            },
        },
        sentinel: true,
        experience: "0.2",
    },
{
        name: [
            "Nymphen",
            "Nymphs",
            "",
            "",
            "",
            "",
        ],
        attack: "0",
        defense: "6",
        life: "44",
        tpv: "4",
        capacity: "0",
        points: "2",
        costs: {
            production: {
                essences: "0",
                crystals: "0",
                stones: "0",
                gold: "0",
                mana: "0",
            },
            revival: {
                stones: "0",
                mushrooms: "0",
            },
        },
        sentinel: true,
        experience: "0",
    },
{
        name: [
            "Schlingpflanzen",
            "Climbing Plants",
            "",
            "",
            "",
            "",
        ],
        attack: "0",
        defense: "7",
        life: "48",
        tpv: "4",
        capacity: "0",
        points: "2",
        costs: {
            production: {
                essences: "0",
                crystals: "0",
                stones: "0",
                gold: "0",
                mana: "0",
            },
            revival: {
                stones: "0",
                mushrooms: "0",
            },
        },
        sentinel: true,
        experience: "0",
    },
{
        name: [
            "Meerjungfrauen",
            "Mermaids",
            "",
            "",
            "",
            "",
        ],
        attack: "6",
        defense: "6",
        life: "120",
        tpv: "2",
        capacity: "70",
        points: "30",
        costs: {
            production: {
                essences: "0",
                crystals: "0",
                stones: "0",
                gold: "0",
                mana: "0",
            },
            revival: {
                stones: "0",
                mushrooms: "0",
            },
        },
        sentinel: true,
        experience: "0.4",
    },
{
        name: [
            "Werwölfe",
            "Werewolves",
            "",
            "",
            "",
            "",
        ],
        attack: "0",
        defense: "9",
        life: "56",
        tpv: "4",
        capacity: "0",
        points: "2",
        costs: {
            production: {
                essences: "0",
                crystals: "0",
                stones: "0",
                gold: "0",
                mana: "0",
            },
            revival: {
                stones: "0",
                mushrooms: "0",
            },
        },
        sentinel: true,
        experience: "0",
    },
{
        name: [
            "Gorgonen",
            "Gorgons",
            "",
            "",
            "",
            "",
        ],
        attack: "0",
        defense: "10",
        life: "66",
        tpv: "4",
        capacity: "0",
        points: "3",
        costs: {
            production: {
                essences: "0",
                crystals: "0",
                stones: "0",
                gold: "0",
                mana: "0",
            },
            revival: {
                stones: "0",
                mushrooms: "0",
            },
        },
        sentinel: true,
        experience: "0",
    },
{
        name: [
            "Harpien",
            "Harpies",
            "",
            "",
            "",
            "",
        ],
        attack: "0",
        defense: "11",
        life: "70",
        tpv: "4",
        capacity: "0",
        points: "3",
        costs: {
            production: {
                essences: "0",
                crystals: "0",
                stones: "0",
                gold: "0",
                mana: "0",
            },
            revival: {
                stones: "0",
                mushrooms: "0",
            },
        },
        sentinel: true,
        experience: "0",
    },
{
        name: [
            "Weißadler",
            "Bald Eagles",
            "",
            "",
            "",
            "",
        ],
        attack: "0",
        defense: "12",
        life: "88",
        tpv: "4",
        capacity: "0",
        points: "3",
        costs: {
            production: {
                essences: "0",
                crystals: "0",
                stones: "0",
                gold: "0",
                mana: "0",
            },
            revival: {
                stones: "0",
                mushrooms: "0",
            },
        },
        sentinel: true,
        experience: "0",
    },
{
        name: [
            "Morlocks",
            "Morlocks",
            "",
            "",
            "",
            "",
        ],
        attack: "0",
        defense: "13",
        life: "100",
        tpv: "4",
        capacity: "0",
        points: "3",
        costs: {
            production: {
                essences: "0",
                crystals: "0",
                stones: "0",
                gold: "0",
                mana: "0",
            },
            revival: {
                stones: "0",
                mushrooms: "0",
            },
        },
        sentinel: true,
        experience: "0",
    },
{
        name: [
            "Riesen Marokspinnen",
            "Giant Marok Spiders",
            "",
            "",
            "",
            "",
        ],
        attack: "0",
        defense: "14",
        life: "110",
        tpv: "4",
        capacity: "0",
        points: "4",
        costs: {
            production: {
                essences: "0",
                crystals: "0",
                stones: "0",
                gold: "0",
                mana: "0",
            },
            revival: {
                stones: "0",
                mushrooms: "0",
            },
        },
        sentinel: true,
        experience: "0",
    },
{
        name: [
            "Feuerteufel",
            "Fire Devils",
            "",
            "",
            "",
            "",
        ],
        attack: "8",
        defense: "8",
        life: "180",
        tpv: "2",
        capacity: "60",
        points: "40",
        costs: {
            production: {
                essences: "0",
                crystals: "0",
                stones: "0",
                gold: "0",
                mana: "0",
            },
            revival: {
                stones: "0",
                mushrooms: "0",
            },
        },
        sentinel: true,
        experience: "0.4",
    },
{
        name: [
            "Fenriswolf",
            "Fenrir Wolves",
            "",
            "",
            "",
            "",
        ],
        attack: "0",
        defense: "16",
        life: "120",
        tpv: "4",
        capacity: "0",
        points: "4",
        costs: {
            production: {
                essences: "0",
                crystals: "0",
                stones: "0",
                gold: "0",
                mana: "0",
            },
            revival: {
                stones: "0",
                mushrooms: "0",
            },
        },
        sentinel: true,
        experience: "0",
    },
{
        name: [
            "Dämon",
            "Demons",
            "",
            "",
            "",
            "",
        ],
        attack: "0",
        defense: "17",
        life: "130",
        tpv: "4",
        capacity: "0",
        points: "5",
        costs: {
            production: {
                essences: "0",
                crystals: "0",
                stones: "0",
                gold: "0",
                mana: "0",
            },
            revival: {
                stones: "0",
                mushrooms: "0",
            },
        },
        sentinel: true,
        experience: "0",
    },
{
        name: [
            "Horngolems",
            "Horn Golems",
            "",
            "",
            "",
            "",
        ],
        attack: "10",
        defense: "10",
        life: "240",
        tpv: "2",
        capacity: "50",
        points: "50",
        costs: {
            production: {
                essences: "0",
                crystals: "0",
                stones: "0",
                gold: "0",
                mana: "0",
            },
            revival: {
                stones: "0",
                mushrooms: "0",
            },
        },
        sentinel: true,
        experience: "0.7",
    },
{
        name: [
            "Sonnenpferde",
            "Sun Horses",
            "",
            "",
            "",
            "",
        ],
        attack: "0",
        defense: "19",
        life: "150",
        tpv: "2",
        capacity: "0",
        points: "6",
        costs: {
            production: {
                essences: "0",
                crystals: "0",
                stones: "0",
                gold: "0",
                mana: "0",
            },
            revival: {
                stones: "0",
                mushrooms: "0",
            },
        },
        sentinel: true,
        experience: "0",
    },
{
        name: [
            "Minotauren",
            "Minotaurs",
            "",
            "",
            "",
            "",
        ],
        attack: "0",
        defense: "20",
        life: "170",
        tpv: "2",
        capacity: "0",
        points: "5",
        costs: {
            production: {
                essences: "0",
                crystals: "0",
                stones: "0",
                gold: "0",
                mana: "0",
            },
            revival: {
                stones: "0",
                mushrooms: "0",
            },
        },
        sentinel: true,
        experience: "0",
    },
{
        name: [
            "Greifen",
            "Gryphons",
            "",
            "",
            "",
            "",
        ],
        attack: "12",
        defense: "12",
        life: "300",
        tpv: "2",
        capacity: "40",
        points: "60",
        costs: {
            production: {
                essences: "0",
                crystals: "0",
                stones: "0",
                gold: "0",
                mana: "0",
            },
            revival: {
                stones: "0",
                mushrooms: "0",
            },
        },
        sentinel: true,
        experience: "0.9",
    },
{
        name: [
            "Blutalben",
            "Blood Alps",
            "",
            "",
            "",
            "",
        ],
        attack: "0",
        defense: "23",
        life: "210",
        tpv: "2",
        capacity: "0",
        points: "7",
        costs: {
            production: {
                essences: "0",
                crystals: "0",
                stones: "0",
                gold: "0",
                mana: "0",
            },
            revival: {
                stones: "0",
                mushrooms: "0",
            },
        },
        sentinel: true,
        experience: "0",
    },
{
        name: [
            "Zyklopen",
            "Cyclopes",
            "",
            "",
            "",
            "",
        ],
        attack: "14",
        defense: "14",
        life: "360",
        tpv: "2",
        capacity: "30",
        points: "70",
        costs: {
            production: {
                essences: "0",
                crystals: "0",
                stones: "0",
                gold: "0",
                mana: "0",
            },
            revival: {
                stones: "0",
                mushrooms: "0",
            },
        },
        sentinel: true,
        experience: "1.0",
    },
{
        name: [
            "Mantikoren",
            "Manticores",
            "",
            "",
            "",
            "",
        ],
        attack: "0",
        defense: "28",
        life: "230",
        tpv: "2",
        capacity: "0",
        points: "9",
        costs: {
            production: {
                essences: "0",
                crystals: "0",
                stones: "0",
                gold: "0",
                mana: "0",
            },
            revival: {
                stones: "0",
                mushrooms: "0",
            },
        },
        sentinel: true,
        experience: "0",
    },
{
        name: [
            "Behemoth",
            "Behemoth",
            "",
            "",
            "",
            "",
        ],
        attack: "16",
        defense: "16",
        life: "420",
        tpv: "2",
        capacity: "20",
        points: "80",
        costs: {
            production: {
                essences: "0",
                crystals: "0",
                stones: "0",
                gold: "0",
                mana: "0",
            },
            revival: {
                stones: "0",
                mushrooms: "0",
            },
        },
        sentinel: true,
        experience: "1.3",
    },
{
        name: [
            "Oger",
            "Ogres",
            "",
            "",
            "",
            "",
        ],
        attack: "0",
        defense: "40",
        life: "300",
        tpv: "2",
        capacity: "0",
        points: "12",
        costs: {
            production: {
                essences: "0",
                crystals: "0",
                stones: "0",
                gold: "0",
                mana: "0",
            },
            revival: {
                stones: "0",
                mushrooms: "0",
            },
        },
        sentinel: true,
        experience: "0",
    },
{
        name: [
            "Sandwürmer",
            "Sand Worms",
            "",
            "",
            "",
            "",
        ],
        attack: "0",
        defense: "50",
        life: "390",
        tpv: "2",
        capacity: "0",
        points: "15",
        costs: {
            production: {
                essences: "0",
                crystals: "0",
                stones: "0",
                gold: "0",
                mana: "0",
            },
            revival: {
                stones: "0",
                mushrooms: "0",
            },
        },
        sentinel: true,
        experience: "0",
    },
{
        name: [
            "Todesengel",
            "Death Angels",
            "",
            "",
            "",
            "",
        ],
        attack: "20",
        defense: "20",
        life: "540",
        tpv: "2",
        capacity: "10",
        points: "90",
        costs: {
            production: {
                essences: "0",
                crystals: "0",
                stones: "0",
                gold: "0",
                mana: "0",
            },
            revival: {
                stones: "0",
                mushrooms: "0",
            },
        },
        sentinel: true,
        experience: "2.5",
    },
{
        name: [
            "Goldene Sphinx",
            "Golden Sphinxes",
            "",
            "",
            "",
            "",
        ],
        attack: "0",
        defense: "80",
        life: "630",
        tpv: "2",
        capacity: "0",
        points: "24",
        costs: {
            production: {
                essences: "0",
                crystals: "0",
                stones: "0",
                gold: "0",
                mana: "0",
            },
            revival: {
                stones: "0",
                mushrooms: "0",
            },
        },
        sentinel: true,
        experience: "0",
    },
{
        name: [
            "Feuerstacheldrachen",
            "Fire Sting Dragons",
            "",
            "",
            "",
            "",
        ],
        attack: "0",
        defense: "80",
        life: "630",
        tpv: "2",
        capacity: "0",
        points: "30",
        costs: {
            production: {
                essences: "0",
                crystals: "0",
                stones: "0",
                gold: "0",
                mana: "0",
            },
            revival: {
                stones: "0",
                mushrooms: "0",
            },
        },
        sentinel: true,
        experience: "0",
    },
{
        name: [
            "Eisaugendrachen",
            "Ice Eye Dragons",
            "",
            "",
            "",
            "",
        ],
        attack: "0",
        defense: "150",
        life: "920",
        tpv: "2",
        capacity: "0",
        points: "40",
        costs: {
            production: {
                essences: "0",
                crystals: "0",
                stones: "0",
                gold: "0",
                mana: "0",
            },
            revival: {
                stones: "0",
                mushrooms: "0",
            },
        },
        sentinel: true,
        experience: "0",
    },
    {
        name: [
            "Schlangenhalsdrachen",
            "Snake Neck Dragon",
            "",
            "",
            "",
            "",
        ],
        attack: "0",
        defense: "200",
        life: "1200",
        tpv: "5",
        capacity: "0",
        points: "50",
        costs: {
            production: {
                essences: "0",
                crystals: "0",
                stones: "0",
                gold: "0",
                mana: "0",
            },
            revival: {
                stones: "0",
                mushrooms: "0",
            },
        },
        sentinel: true,
        experience: "0",
    },
];

function getUnitFromName(name) {
    return unitValues.filter(element => {
        return element.name.filter(element => {
            return element === name;
        }).length > 0;
    });

}